CC = gcc
CFLAGS = -g -std=c90

Newest.exe: ../all/char.c ../all/turn.c ../all/location.c ../all/piece.c ../all/filereading.c ../all/chess.c ../all/mischelp.c ../all/logichelp.c ../all/tests.c ../all/commands.c main.c
	$(CC) $(CFLAGS) -o $@ $^
